# Generated by Django 5.0.7 on 2024-07-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фото пользователя",
                null=True,
                upload_to="users",
                verbose_name="Фото",
            ),
        ),
    ]
