# Generated by Django 5.0.7 on 2024-07-25 10:01

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Укажите электронную почту",
                        max_length=60,
                        unique=True,
                        verbose_name="Электронная почта",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="Введите номер телефона",
                        max_length=128,
                        null=True,
                        region="RU",
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        help_text="Введите комментарий",
                        max_length=60,
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.CreateModel(
            name="HistoryNewsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Укажите дату и время",
                        verbose_name="Дата и время",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="Укажите статус рассылки",
                        max_length=60,
                        null=True,
                        verbose_name="Статус рассылки",
                    ),
                ),
                (
                    "response",
                    models.CharField(
                        blank=True,
                        help_text="Укажите ответ почтового сервиса",
                        max_length=60,
                        null=True,
                        verbose_name="Ответ почтового сервиса",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Напишите тему сообщения",
                        max_length=60,
                        verbose_name="Тема",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Напишите сообщение", verbose_name="Сообщение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_time",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        help_text="Укажите дату и время",
                        null=True,
                        verbose_name="Дата и время",
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        blank=True,
                        help_text="Укажите периодичность",
                        max_length=60,
                        null=True,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="Укажите статус рассылки",
                        max_length=60,
                        null=True,
                        verbose_name="Статус рассылки",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Укажите пользователя",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "clients",
                    models.ManyToManyField(
                        help_text="Укажите клиентов",
                        to="newsletter.client",
                        verbose_name="Клиенты",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите сообщение",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="newsletter.message",
                        verbose_name="Сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
