# Generated by Django 5.0.7 on 2024-08-11 15:06

import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Укажите электронную почту",
                        max_length=60,
                        unique=True,
                        verbose_name="Электронная почта",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="Введите номер телефона",
                        max_length=128,
                        null=True,
                        region="RU",
                        unique=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        help_text="Укажите Ф.И.О.",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Ф.И.О.",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        help_text="Введите комментарий",
                        max_length=100,
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.CreateModel(
            name="HistoryNewsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Укажите дату и время рассылки",
                        verbose_name="Дата и время рассылки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="Укажите статус рассылки",
                        max_length=100,
                        null=True,
                        verbose_name="Статус рассылки",
                    ),
                ),
                (
                    "response",
                    models.CharField(
                        blank=True,
                        help_text="Укажите ответ почтового сервиса",
                        max_length=255,
                        null=True,
                        verbose_name="Ответ почтового сервиса",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Напишите тему сообщения",
                        max_length=100,
                        verbose_name="Тема",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Напишите сообщение", verbose_name="Сообщение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "permissions": [("can_view_message", "Can view message")],
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название рассылки",
                        max_length=100,
                        verbose_name="Название рассылки",
                    ),
                ),
                (
                    "date_time",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        help_text="Укажите дату и время создания",
                        null=True,
                        verbose_name="Дата и время создания",
                    ),
                ),
                (
                    "date_start",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Укажите дату начала рассылки",
                        verbose_name="Дата начала рассылки",
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OD", "раз в день"),
                            ("OW", "раз в неделю"),
                            ("OM", "раз в месяц"),
                        ],
                        help_text="Укажите периодичность",
                        max_length=100,
                        null=True,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CR", "создана"),
                            ("LA", "запущена"),
                            ("CO", "завершена"),
                        ],
                        default="CR",
                        help_text="Укажите статус рассылки",
                        max_length=100,
                        verbose_name="Статус рассылки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
