# Generated by Django 5.0.7 on 2024-07-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="full_name",
            field=models.CharField(
                blank=True,
                help_text="Укажите Ф.И.О.",
                max_length=255,
                null=True,
                verbose_name="Ф.И.О.",
            ),
        ),
    ]
