# Generated by Django 5.0.7 on 2024-07-30 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("newsletter", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите автора",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите пользователя",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="clients",
            field=models.ManyToManyField(
                help_text="Укажите клиентов",
                to="newsletter.client",
                verbose_name="Клиенты",
            ),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="message",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите сообщение",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="newsletter.message",
                verbose_name="Сообщение",
            ),
        ),
    ]
