# Generated by Django 5.0.7 on 2024-08-11 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "permissions": [("can_view_client", "Can view client")],
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "permissions": [
                    ("can_view_newsletter", "Can view newsletter"),
                    ("can_change_newsletter", "Can change newsletter"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
