# Generated by Django 5.0.7 on 2024-07-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0002_client_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="periodicity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OD", "раз в день"),
                    ("OW", "раз в неделю"),
                    ("OM", "раз в месяц"),
                ],
                help_text="Укажите периодичность",
                max_length=60,
                null=True,
                verbose_name="Периодичность",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="status",
            field=models.CharField(
                choices=[("CR", "создана"), ("LA", "запущена"), ("CO", "завершена")],
                default="создана",
                help_text="Укажите статус рассылки",
                max_length=60,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
