# Generated by Django 5.0.7 on 2024-07-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="clients",
            field=models.ManyToManyField(
                help_text="Укажите клиентов",
                related_name="clients",
                to="newsletter.client",
                verbose_name="Клиенты",
            ),
        ),
    ]
