# Generated by Django 5.0.7 on 2024-08-11 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0003_alter_client_options_alter_newsletter_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "permissions": [
                    ("can_add_client", "Can add client"),
                    ("can_view_client", "Can view client"),
                    ("can_change_client", "Can change client"),
                    ("can_delete_client", "Can delete client"),
                ],
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [
                    ("can_add_message", "Can add message"),
                    ("can_view_message", "Can view message"),
                    ("can_change_message", "Can change message"),
                    ("can_delete_message", "Can delete message"),
                ],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "permissions": [
                    ("can_add_newsletter", "Can add newsletter"),
                    ("can_view_newsletter", "Can view newsletter"),
                    ("can_change_newsletter", "Can change newsletter"),
                    ("can_delete_newsletter", "Can delete newsletter"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
