# Generated by Django 5.0.7 on 2024-08-01 07:29

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0004_newsletter_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="full_name",
            field=models.CharField(
                blank=True,
                help_text="Укажите Ф.И.О.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Ф.И.О.",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Введите номер телефона",
                max_length=128,
                null=True,
                region="RU",
                unique=True,
                verbose_name="Номер телефона",
            ),
        ),
    ]
