# Generated by Django 5.0.7 on 2024-08-03 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0006_client_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [("can_view_message", "Can view message")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
