# Generated by Django 5.0.7 on 2024-08-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0007_alter_message_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="status",
            field=models.CharField(
                choices=[("CR", "создана"), ("LA", "запущена"), ("CO", "завершена")],
                default="CR",
                help_text="Укажите статус рассылки",
                max_length=60,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
