# Generated by Django 5.0.7 on 2024-08-06 09:45

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0008_alter_newsletter_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="date_start",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 8, 6, 9, 45, 44, 339331, tzinfo=datetime.timezone.utc
                ),
                help_text="Укажите дату начала рассылки",
                verbose_name="Дата начала рассылки",
            ),
        ),
    ]
