# Generated by Django 5.0.7 on 2024-08-06 09:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0009_newsletter_date_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="date_start",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Укажите дату начала рассылки",
                verbose_name="Дата начала рассылки",
            ),
        ),
    ]
