# Generated by Django 5.0.7 on 2024-08-06 14:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0010_alter_newsletter_date_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="date_time",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                help_text="Укажите дату и время создания",
                null=True,
                verbose_name="Дата и время создания",
            ),
        ),
    ]
