# Generated by Django 5.0.7 on 2024-08-06 17:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0011_alter_newsletter_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historynewsletter",
            name="date_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Укажите дату и время рассылки",
                verbose_name="Дата и время рассылки",
            ),
        ),
    ]
