# Generated by Django 5.0.7 on 2024-08-06 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0012_alter_historynewsletter_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="historynewsletter",
            name="newsletter",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите рассылку",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="newsletter.newsletter",
                verbose_name="Рассылка",
            ),
        ),
    ]
