# Generated by Django 5.0.7 on 2024-08-06 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0014_historynewsletter_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historynewsletter",
            name="author",
        ),
    ]
