# Generated by Django 5.0.7 on 2024-08-11 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "permissions": [
                    ("can_add_blog", "Can add blog"),
                    ("can_view_blog", "Can view blog"),
                    ("can_change_blog", "Can change blog"),
                    ("can_delete_blog", "Can delete blog"),
                ],
                "verbose_name": "Блог",
                "verbose_name_plural": "Блог",
            },
        ),
    ]
